* Description

"Meldrake! Help!" Glynis cried. Her voice was quickly receding from Meldrake's hearing. "I don't know how to stop!"

They weren't very far from the lake's surface now. Meldrake, sensing the danger as his friend plummeted down and down, tucked in his wings with surprising quickness and dove head-first, an ebony rocket. Even as he did so, he began chanting a diving spell, the words of power which served to focus his mind on the target, who was after all also his friend:

#+begin_verse
/White streak, Black streak, Down we go together!/
/Sizzle! Snap!  Thunder-crack!  Down we go forever!/
/Down I go to save my friend, To live up to my names:/
/And the Black Arrow strikes Where the Black Heart aims!/
#+end_verse

---

Twelve-year-old Glynis McGinty works in the laundry room at a Victorian-era hotel near her home in the mountains. One day, she discovers a stained glass door in the basement storage, one decorated with a strange motif, and which holds an even stranger appeal: on the other side of that door are Meldrake the Raven and various (soon-to-be) friends, enemies, and others who fall somewhere in between. They are all inhabitants of a world rather like our own, equal parts magical and measurable, where bears and ravens speak in their own secret tongues and live in towns and cities of their own making. 

Over them all falls the long shadow of Jelec, the White Bear, who is also called the Protector, though no one still living can remember why he should have such a name. In fact, he has not been sighted in the realm which some call his in many years, and another power rises, one that aspires to hold the realm for its own.

* Marketing Blurb
Read the complete first chapter of my book for free: JELEC: THE WHITE BEAR, *or, Beware an Encounter with a Raven and his Friends*.

Be prepared for a rambling tale involving verse poetry, magic spells (which are in fact the very same thing), mathematics, snow, hexagons, moons, combinations, constellations, mountains, magic trees, and teleportation.

Some of my direct influences include Neal Stephenson, Richard Adams, Tolkien, Lewis, Gary Gygax, and Martin Gardner.

It's available on Amazon here: http://www.amazon.com/dp/B006U337YW
Read the first chapter here: http://jelec.wordpress.com/2012/01/09/jelec-the-complete-first-chapter/

* Chapter Listing:

Things that Slip Through the cracks
Honey Dragon
Glynis and Tree
Wedding Cake Boats
The Language of Birds
The Numbermaster's Hall
Silverbird and the Starling King
Long River's Edge
The Badger who Studied Verse
A Simple Recipe
Interlude: The King's Dream
